version: 2

project_name: versource

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: macos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

dockers_v2:
  - images:
      - "ghcr.io/marcbran/{{ .ProjectName }}"
    tags:
      - "{{ if .IsSnapshot }}SNAPSHOT{{ else }}{{ end }}"
      - "{{ .Tag }}{{ if .IsSnapshot }}-SNAPSHOT{{ else }}{{ end }}"
      - "v{{ .Major }}{{ if .IsSnapshot }}-SNAPSHOT{{ else }}{{ end }}"
      - "v{{ .Major }}.{{ .Minor }}{{ if .IsSnapshot }}-SNAPSHOT{{ else }}{{ end }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
