set fallback := true

default:
    @just --list

release: test
    @jsonnet-kit release -r https://github.com/marcbran/jsonnet.git -b versource-plugin/github -p versource-plugin-github

test:
    @jsonnet-kit test
